# ---------------------------------------------------------------------------
#  CD WORKFLOW
#  Purpose : Build a Docker image, push it to GHCR and deploy it
#            to the appropriate environment (dev or production).
#  Trigger : push events to dev or master.
# ---------------------------------------------------------------------------
name: continuous deployment pipeline

on:
  push:
    branches:
      - dev
      - master

jobs:
  # -------------------------------------------------------------------------
  # 1. Build-and-Push job  (runs on GitHub-hosted runner)
  #    - Builds image and pushes to GHCR.
  # -------------------------------------------------------------------------
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read    # Needed to push to ghcr.io
    # Guard-clause so the job doesn’t run for other branches
    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v3
      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      # Build the Docker image and expose the tag to later jobs

      - name: Build Docker image
        run: |
          IMAGE_TAG=ghcr.io/preciousdipe/1791-devops-task:${{ github.ref_name }}-${{ github.run_number }}
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          docker build -t $IMAGE_TAG .

      # Push image to GHCR
      - name: Push Docker image
        run: |
          docker push $IMAGE_TAG

  # -------------------------------------------------------------------------
  # 2. Deploy-Dev job  (runs on self-hosted runner)
  #    - Executes only for the dev branch.
  # -------------------------------------------------------------------------
  deploy-dev:
    runs-on: self-hosted
    needs: build-and-push
    if: github.ref == 'refs/heads/dev'
    environment:
      name: development
    steps:
      - uses: actions/checkout@v3
       # Start SSH agent with private key stored in GitHub Secrets
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      # Pull and run container on the development server
      - name: Deploy to dev environment
        run: |
          IMAGE_TAG=ghcr.io/preciousdipe/1791-devops-task:dev-${{ github.run_number }}
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << EOF
            set -e
            docker stop app || true && docker rm app || true
            docker pull $IMAGE_TAG
            docker run -d --name app -p 80:80 $IMAGE_TAG
          EOF

  # -------------------------------------------------------------------------
  # 3. Deploy-Prod job  (runs on self-hosted runner)
  #    - Executes only for the master branch.
  # -------------------------------------------------------------------------
  deploy-prod:
    runs-on: self-hosted
    needs: build-and-push
    if: github.ref == 'refs/heads/master'
    environment:
      name: production
    steps:
      - uses: actions/checkout@v3
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to production environment
        run: |
          IMAGE_TAG=ghcr.io/preciousdipe/1791-devops-task:master-${{ github.run_number }}
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << EOF
            set -e
            docker stop app || true && docker rm app || true
            docker pull $IMAGE_TAG
            docker run -d --name app -p 80:80 $IMAGE_TAG
          EOF