# ---------------------------------------------------------------------------
#  CI WORKFLOW
#  Purpose : Lint and test every pull request before code is merged.
#  Trigger : pull_request events targeting dev or master.
# ---------------------------------------------------------------------------
name: continous integration pipeline
on:
  # Run the jobs for every PR opened against the main branches
  pull_request:
    branches:
      - master
      - dev

jobs:
  # -------------------------------------------------------------------------
  # 1. Lint job
  #    - Checks code style with flake8.
  # -------------------------------------------------------------------------
  lint:
    runs-on: ubuntu-latest
    steps:
      # Checkout the PR’s code
      - uses: actions/checkout@v3
      # Install Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      # install dependecies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      # run flake*
      - name: Run Flake8
        run: flake8 .

  # -------------------------------------------------------------------------
  # 2. Test job
  #    - Installs dependencies and executes pytest.
  # -------------------------------------------------------------------------
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        run: |
          export PYTHONPATH=.
          pytest