name: continuous deployment pipeline

on:
  push:
    branches:
      - dev
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # ✅ Using GITHUB_TOKEN to authenticate to GHCR
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # ✅ Alternative (fallback) using PAT stored in GHCR_PAT
      # Uncomment if GITHUB_TOKEN fails and GHCR_PAT is set in your secrets
      # - name: Log in to GHCR with PAT
      #   run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u preciousdipe --password-stdin

      - name: Build Docker image
        run: |
          IMAGE_TAG=ghcr.io/preciousdipe/1791-devops-task:${{ github.ref_name }}-${{ github.run_number }}
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          docker build -t $IMAGE_TAG .

      - name: Push Docker image
        run: |
          docker push $IMAGE_TAG

  deploy-dev:
    runs-on: self-hosted
    needs: build-and-push
    if: github.ref == 'refs/heads/dev'
    environment:
      name: development
    steps:
      - uses: actions/checkout@v3
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to dev environment
        run: |
          IMAGE_TAG=ghcr.io/preciousdipe/1791-devops-task:dev-${{ github.run_number }}
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << EOF
            set -e
            docker stop app || true && docker rm app || true
            docker pull $IMAGE_TAG
            docker run -d --name app -p 80:80 $IMAGE_TAG
          EOF

  deploy-prod:
    runs-on: self-hosted
    needs: build-and-push
    if: github.ref == 'refs/heads/master'
    environment:
      name: production
    steps:
      - uses: actions/checkout@v3
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to production environment
        run: |
          IMAGE_TAG=ghcr.io/preciousdipe/1791-devops-task:master-${{ github.run_number }}
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << EOF
            set -e
            docker stop app || true && docker rm app || true
            docker pull $IMAGE_TAG
            docker run -d --name app -p 80:80 $IMAGE_TAG
          EOF